version: "3"
services:
  database:
    image: postgres
    restart: always
    ports:
    - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: "${DATABASE}"
